/**
 * PDF generation utility for Taliq HR letters.
 * Uses jsPDF for direct PDF download — no print dialog, no popup.
 */
import { jsPDF } from "jspdf";

interface LetterData {
  ref?: string;
  letterType: string;
  employeeName: string;
  employeeId: string;
  position: string;
  department: string;
  joinDate: string;
  nationality?: string;
  totalSalary: number;
  basicSalary: number;
  housingAllowance: number;
  transportAllowance: number;
  grade?: string;
  letterDate: string;
  purpose?: string;
  addressedTo?: string;
  companyName?: string;
  signatoryName?: string;
  signatoryTitle?: string;
}

interface SalaryData {
  employeeName: string;
  employeeId: string;
  position: string;
  department: string;
  month: string;
  basic: number;
  housing: number;
  transport: number;
  grossPay: number;
  gosiAmount: number;
  totalLoanDeduction: number;
  totalDeductions: number;
  netPay: number;
  currency: string;
}

const TYPE_LABELS: Record<string, string> = {
  employment_certificate: "Employment Certificate",
  salary_certificate: "Salary Certificate",
  experience_letter: "Experience Letter",
  noc_letter: "No Objection Certificate (NOC)",
  bank_letter: "Bank Letter",
  promotion_letter: "Promotion Letter",
};

function addHeader(doc: jsPDF, companyName: string) {
  // Company header
  doc.setFillColor(16, 185, 129); // emerald-500
  doc.rect(0, 0, 210, 3, "F");
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(16, 185, 129);
  doc.text(companyName || "MORABAHA MRNA", 20, 22);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text("Kingdom of Saudi Arabia", 20, 28);
  
  // Separator line
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(0.5);
  doc.line(20, 33, 190, 33);
}

function addFooter(doc: jsPDF, ref: string, empId: string, page: number) {
  const y = 275;
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(20, y, 190, y);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(160, 160, 160);
  doc.text(`Ref: ${ref} | Employee: ${empId} | Generated by Taliq HR Platform`, 20, y + 5);
  doc.text(`Page ${page}`, 190, y + 5, { align: "right" });
}

export function generateLetterPDF(data: LetterData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const company = data.companyName || "MORABAHA MRNA";
  const label = TYPE_LABELS[data.letterType] || data.letterType;
  
  addHeader(doc, company);
  
  // Date
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(data.letterDate, 190, 42, { align: "right" });
  
  // To
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text("To:", 20, 50);
  doc.setFont("helvetica", "bold");
  doc.text(data.addressedTo || "To Whom It May Concern", 30, 50);
  
  // Subject
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  const subjectText = `RE: ${label}`;
  const subjectWidth = doc.getTextWidth(subjectText);
  doc.text(subjectText, 105 - subjectWidth / 2, 64);
  doc.setDrawColor(30, 30, 30);
  doc.setLineWidth(0.3);
  doc.line(105 - subjectWidth / 2 - 2, 65, 105 + subjectWidth / 2 + 2, 65);
  
  // Body
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  
  let y = 78;
  const lineHeight = 6;
  const maxWidth = 165;
  
  const bodyParts = getLetterBody(data);
  for (const para of bodyParts) {
    const lines = doc.splitTextToSize(para, maxWidth);
    for (const line of lines) {
      if (y > 240) {
        addFooter(doc, data.ref || "N/A", data.employeeId, 1);
        doc.addPage();
        addHeader(doc, company);
        y = 42;
      }
      doc.text(line, 20, y);
      y += lineHeight;
    }
    y += 4; // paragraph gap
  }
  
  // Salary table for salary cert / bank letter
  if (data.letterType === "salary_certificate" || data.letterType === "bank_letter") {
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("Compensation Details:", 20, y);
    y += 8;
    
    const rows = [
      ["Basic Salary", `${data.basicSalary?.toLocaleString()} SAR`],
      ["Housing Allowance", `${data.housingAllowance?.toLocaleString()} SAR`],
      ["Transport Allowance", `${data.transportAllowance?.toLocaleString()} SAR`],
      ["Total Monthly Salary", `${data.totalSalary?.toLocaleString()} SAR`],
    ];
    
    for (const [label, val] of rows) {
      const isTotal = label === "Total Monthly Salary";
      doc.setFont("helvetica", isTotal ? "bold" : "normal");
      doc.setFontSize(10);
      if (isTotal) {
        doc.setFillColor(240, 253, 244); // emerald-50
        doc.rect(20, y - 4, 165, 7, "F");
      }
      doc.setTextColor(60, 60, 60);
      doc.text(label, 25, y);
      doc.text(val, 180, y, { align: "right" });
      y += 7;
    }
    y += 4;
  }
  
  // Closing
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  const closingLines = doc.splitTextToSize(
    "Should you require any further information, please do not hesitate to contact the Human Resources department.",
    maxWidth
  );
  for (const line of closingLines) {
    doc.text(line, 20, y);
    y += lineHeight;
  }
  
  // Signature
  y += 20;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Yours sincerely,", 20, y);
  y += 25;
  doc.setDrawColor(150, 150, 150);
  doc.line(20, y, 80, y);
  y += 5;
  doc.setFont("helvetica", "bold");
  doc.text(data.signatoryName || "Authorized Signatory", 20, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(data.signatoryTitle || "Human Resources Department", 20, y);
  
  addFooter(doc, data.ref || "N/A", data.employeeId, 1);
  
  const filename = `${data.letterType}_${data.employeeId}_${data.letterDate}.pdf`;
  doc.save(filename);
}

function getLetterBody(p: LetterData): string[] {
  switch (p.letterType) {
    case "employment_certificate":
      return [
        `This is to certify that ${p.employeeName} (Employee ID: ${p.employeeId}, Nationality: ${p.nationality || "N/A"}) has been employed at our organization as ${p.position} in the ${p.department} department since ${p.joinDate}.`,
        p.purpose ? `This certificate is issued upon the employee's request for the purpose of ${p.purpose}.` : "This certificate is issued upon the employee's request.",
      ];
    case "salary_certificate":
      return [
        `This is to certify that ${p.employeeName} (Employee ID: ${p.employeeId}) is currently employed as ${p.position} in the ${p.department} department.`,
        "The employee's monthly compensation details are as follows:",
      ];
    case "experience_letter":
      return [
        `This is to certify that ${p.employeeName} (Employee ID: ${p.employeeId}) has been working with our organization since ${p.joinDate} as ${p.position} in the ${p.department} department.`,
        "During their tenure, they have demonstrated excellent professional conduct, dedication, and competence in their role. We wish them continued success in all their future endeavors.",
      ];
    case "noc_letter":
      return [
        `This is to confirm that we have No Objection to ${p.employeeName} (Employee ID: ${p.employeeId}), currently employed as ${p.position} in the ${p.department} department${p.purpose ? `, for the purpose of ${p.purpose}` : ""}.`,
        "This NOC is issued at the employee's request and does not relieve them of their current contractual obligations with the organization.",
      ];
    case "bank_letter":
      return [
        `This is to confirm that ${p.employeeName} (Employee ID: ${p.employeeId}) is a full-time employee of our organization, serving as ${p.position} in the ${p.department} department since ${p.joinDate}.`,
        "The employee's salary is credited monthly to their bank account via the Wage Protection System (WPS). Details as follows:",
      ];
    case "promotion_letter":
      return [
        `We are pleased to confirm that ${p.employeeName} (Employee ID: ${p.employeeId}) has been promoted to the position of ${p.position} in the ${p.department} department, effective immediately.`,
        "This promotion is in recognition of their outstanding dedication, performance, and valuable contributions to the organization. We are confident they will continue to excel in their new role.",
      ];
    default:
      return [`This letter is issued for ${p.employeeName} (${p.employeeId}).`];
  }
}

export function generatePayslipPDF(data: SalaryData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  addHeader(doc, "MORABAHA MRNA");
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text(`Pay Slip — ${data.month}`, 105, 45, { align: "center" });
  
  // Employee info
  let y = 58;
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(20, y - 4, 170, 22, 3, 3, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("Employee", 25, y + 1); doc.text("ID", 85, y + 1); doc.text("Position", 115, y + 1);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text(data.employeeName, 25, y + 8); doc.text(data.employeeId, 85, y + 8); doc.text(data.position, 115, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Department: ${data.department}`, 25, y + 14);
  
  y = 86;
  // Earnings
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(16, 185, 129);
  doc.text("Earnings", 25, y);
  y += 7;
  
  const earnings = [
    ["Basic Salary", data.basic],
    ["Housing Allowance", data.housing],
    ["Transport Allowance", data.transport],
  ];
  
  for (const [label, val] of earnings) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(label as string, 25, y);
    doc.text(`${(val as number).toLocaleString()} ${data.currency}`, 180, y, { align: "right" });
    y += 6;
  }
  doc.setDrawColor(16, 185, 129);
  doc.line(25, y, 185, y);
  y += 5;
  doc.setFont("helvetica", "bold");
  doc.text("Gross Pay", 25, y);
  doc.text(`${data.grossPay.toLocaleString()} ${data.currency}`, 180, y, { align: "right" });
  
  y += 14;
  // Deductions
  doc.setTextColor(239, 68, 68);
  doc.text("Deductions", 25, y);
  y += 7;
  
  const deductions = [
    ["GOSI Contribution", data.gosiAmount],
    ["Loan Deductions", data.totalLoanDeduction],
  ];
  
  for (const [label, val] of deductions) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text(label as string, 25, y);
    doc.text(`-${(val as number).toLocaleString()} ${data.currency}`, 180, y, { align: "right" });
    y += 6;
  }
  doc.setDrawColor(239, 68, 68);
  doc.line(25, y, 185, y);
  y += 5;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60, 60, 60);
  doc.text("Total Deductions", 25, y);
  doc.text(`-${data.totalDeductions.toLocaleString()} ${data.currency}`, 180, y, { align: "right" });
  
  y += 14;
  // Net Pay
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(20, y - 5, 170, 14, 3, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(16, 185, 129);
  doc.text("Net Pay", 25, y + 3);
  doc.text(`${data.netPay.toLocaleString()} ${data.currency}`, 180, y + 3, { align: "right" });
  
  addFooter(doc, "", data.employeeId, 1);
  doc.save(`payslip_${data.employeeId}_${data.month.replace(/\s/g, "_")}.pdf`);
}


// ── Template-aware PDF generation ────────────────────────────

interface TemplateData {
  type: string;
  name: string;
  body_html: string;
  header: {
    companyName?: string;
    companyNameAr?: string;
    subtitle?: string;
    accentColor?: string;
  };
  footer: {
    signatoryName?: string;
    signatoryTitle?: string;
    showRef?: boolean;
    showDate?: boolean;
    disclaimer?: string;
  };
}

let _templateCache: TemplateData[] | null = null;

async function fetchTemplates(): Promise<TemplateData[]> {
  if (_templateCache) return _templateCache;
  try {
    const res = await fetch("/api/templates");
    if (res.ok) {
      _templateCache = await res.json();
      return _templateCache!;
    }
  } catch { /* fallback to hardcoded */ }
  return [];
}

function renderMustache(template: string, vars: Record<string, string>): string {
  let result = template;
  for (const [key, val] of Object.entries(vars)) {
    result = result.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), val || "");
  }
  result = result.replace(/\{\{#if (\w+)\}\}([\s\S]*?)\{\{\/if\}\}/g, (_, v, content) => {
    return vars[v] ? content : "";
  });
  result = result.replace(/\{\{[^}]+\}\}/g, "");
  result = result.replace(/\\n/g, "\n");
  return result;
}

function stripHtml(html: string): string {
  return html
    .replace(/<strong>/g, "").replace(/<\/strong>/g, "")
    .replace(/<br\s*\/?>/g, "\n")
    .replace(/<table[^>]*>[\s\S]*?<\/table>/g, "")
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/\n\n+/g, "\n\n")
    .trim();
}

export async function generateLetterPDFFromTemplate(data: LetterData) {
  const templates = await fetchTemplates();
  const tpl = templates.find(t => t.type === data.letterType);

  if (!tpl) {
    // Fallback to hardcoded generation
    return generateLetterPDF(data);
  }

  const vars: Record<string, string> = {
    employeeName: data.employeeName,
    employeeId: data.employeeId,
    nationality: data.nationality || "N/A",
    position: data.position,
    department: data.department,
    joinDate: data.joinDate,
    purpose: data.purpose || "",
    companyName: tpl.header.companyName || data.companyName || "MORABAHA MRNA",
    basicSalary: data.basicSalary?.toLocaleString() || "0",
    housingAllowance: data.housingAllowance?.toLocaleString() || "0",
    transportAllowance: data.transportAllowance?.toLocaleString() || "0",
    totalSalary: data.totalSalary?.toLocaleString() || "0",
    letterDate: data.letterDate,
    addressedTo: data.addressedTo || "To Whom It May Concern",
  };

  const renderedBody = stripHtml(renderMustache(tpl.body_html, vars));
  const company = tpl.header.companyName || data.companyName || "MORABAHA MRNA";
  const accent = tpl.header.accentColor || "#10B981";
  const accentRGB = hexToRgb(accent);

  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // Header with template accent color
  doc.setFillColor(accentRGB.r, accentRGB.g, accentRGB.b);
  doc.rect(0, 0, 210, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(accentRGB.r, accentRGB.g, accentRGB.b);
  doc.text(company, 20, 22);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(tpl.header.subtitle || "Kingdom of Saudi Arabia", 20, 28);
  doc.setDrawColor(accentRGB.r, accentRGB.g, accentRGB.b);
  doc.setLineWidth(0.5);
  doc.line(20, 33, 190, 33);

  // Date
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(data.letterDate, 190, 42, { align: "right" });

  // To
  doc.setTextColor(60, 60, 60);
  doc.text("To:", 20, 50);
  doc.setFont("helvetica", "bold");
  doc.text(vars.addressedTo, 30, 50);

  // Subject
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  const subject = `RE: ${tpl.name}`;
  const sw = doc.getTextWidth(subject);
  doc.text(subject, 105 - sw / 2, 64);
  doc.setDrawColor(30, 30, 30);
  doc.setLineWidth(0.3);
  doc.line(105 - sw / 2 - 2, 65, 105 + sw / 2 + 2, 65);

  // Body
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  let y = 78;
  const paragraphs = renderedBody.split("\n\n").filter(p => p.trim());
  for (const para of paragraphs) {
    const lines = doc.splitTextToSize(para.trim(), 165);
    for (const line of lines) {
      if (y > 240) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 20, y);
      y += 6;
    }
    y += 4;
  }

  // Salary table for salary/bank letters
  if (data.letterType === "salary_certificate" || data.letterType === "bank_letter") {
    y += 4;
    const rows = [
      ["Basic Salary", `${data.basicSalary?.toLocaleString()} SAR`],
      ["Housing Allowance", `${data.housingAllowance?.toLocaleString()} SAR`],
      ["Transport Allowance", `${data.transportAllowance?.toLocaleString()} SAR`],
      ["Total Monthly Salary", `${data.totalSalary?.toLocaleString()} SAR`],
    ];
    for (const [label, val] of rows) {
      const isTotal = label.includes("Total");
      doc.setFont("helvetica", isTotal ? "bold" : "normal");
      doc.setFontSize(10);
      if (isTotal) {
        doc.setFillColor(240, 253, 244);
        doc.rect(20, y - 4, 165, 7, "F");
      }
      doc.setTextColor(60, 60, 60);
      doc.text(label, 25, y);
      doc.text(val, 180, y, { align: "right" });
      y += 7;
    }
    y += 4;
  }

  // Closing
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  const closing = doc.splitTextToSize("Should you require any further information, please do not hesitate to contact the Human Resources department.", 165);
  for (const line of closing) { doc.text(line, 20, y); y += 6; }

  // Signature from template footer
  y += 20;
  doc.setFontSize(10);
  doc.text("Yours sincerely,", 20, y);
  y += 25;
  doc.setDrawColor(150, 150, 150);
  doc.line(20, y, 80, y);
  y += 5;
  doc.setFont("helvetica", "bold");
  doc.text(tpl.footer.signatoryName || "Authorized Signatory", 20, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(tpl.footer.signatoryTitle || "Human Resources Department", 20, y);

  // Footer
  const fy = 275;
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(20, fy, 190, fy);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(160, 160, 160);
  const footerParts: string[] = [];
  if (tpl.footer.showRef !== false) footerParts.push(`Ref: ${data.ref || "N/A"}`);
  if (tpl.footer.showDate !== false) footerParts.push(`Date: ${data.letterDate}`);
  footerParts.push(`Employee: ${data.employeeId}`);
  footerParts.push("Generated by Taliq HR Platform");
  doc.text(footerParts.join(" | "), 20, fy + 5);
  if (tpl.footer.disclaimer) {
    doc.text(tpl.footer.disclaimer, 20, fy + 9);
  }

  doc.save(`${data.letterType}_${data.employeeId}_${data.letterDate}.pdf`);
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16),
  } : { r: 16, g: 185, b: 129 };
}
